In [4]:
# This is the final project of the course
# We will create a Random Forest Classifier to predict Loan Approvals
# Importing Libraries
import numpy as np
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn import metrics
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

In [5]:
# Stored the of "loan-prediction-data" in object Loan_Data
Loan_Data = pd.read_excel("loan-prediction-data.xlsx")
Loan_Data.head()

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0.0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1.0,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0.0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,0.0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,LP001008,Male,No,0.0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y

In [6]:
Loan_Data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Loan_ID            614 non-null    object
 1   Gender             601 non-null    object
 2   Married            611 non-null    object
 3   Dependents         599 non-null    float64
 4   Education          614 non-null    object
 5   Self_Employed      582 non-null    object
 6   ApplicantIncome    614 non-null    int64
 7   CoapplicantIncome  614 non-null    float64
 8   LoanAmount         592 non-null    float64
 9   Loan_Amount_Term   600 non-null    float64
 10  Credit_History     564 non-null    float64
 11  Property_Area      614 non-null    object
 12  Loan_Status        614 non-null    object
dtypes: float64(5), int64(1), object(7)
memory usage: 62.5+ KB

In [7]:
Loan_Data.isnull().sum()

Loan_ID               0
Gender               13
Married               3
Dependents           15
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64

In [8]:
Loan_Data["Credit_History"] = Loan_Data["Credit_History"].fillna(Loan_Data["Credit_History"].mode()[0])
Loan_Data["Self_Employed"] = Loan_Data["Self_Employed"].fillna(Loan_Data["Self_Employed"].mode()[0])
Loan_Data["Dependents"] = Loan_Data["Dependents"].fillna(Loan_Data["Dependents"].mode()[0])
Loan_Data["Gender"] = Loan_Data["Gender"].fillna(Loan_Data["Gender"].mode()[0])
Loan_Data["LoanAmount"] = Loan_Data["LoanAmount"].fillna(Loan_Data["LoanAmount"].mean())
Loan_Data.dropna(inplace=True)
# dipalying the frist 5 row 
Loan_Data.head()

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0.0,Graduate,No,5849,0.0,146.412162,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1.0,Graduate,No,4583,1508.0,128.000000,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0.0,Graduate,Yes,3000,0.0,66.000000,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,0.0,Not Graduate,No,2583,2358.0,120.000000,360.0,1.0,Urban,Y
4,LP001008,Male,No,0.0,Graduate,No,6000,0.0,141.000000,360.0,1.0,Urban,Y

In [9]:
# checking the total null value from laon_Data file througth the isnull function 
Loan_Data.isnull().sum()

Loan_ID              0
Gender               0
Married              0
Dependents           0
Education            0
Self_Employed        0
ApplicantIncome      0
CoapplicantIncome    0
LoanAmount           0
Loan_Amount_Term     0
Credit_History       0
Property_Area        0
Loan_Status          0
dtype: int64

In [10]:
Loan_Data.describe()
# cheackiing the information of data on the loan_Data
Loan_Data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 597 entries, 0 to 613
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Loan_ID            597 non-null    object
 1   Gender             597 non-null    object
 2   Married            597 non-null    object
 3   Dependents         597 non-null    float64
 4   Education          597 non-null    object
 5   Self_Employed      597 non-null    object
 6   ApplicantIncome    597 non-null    int64
 7   CoapplicantIncome  597 non-null    float64
 8   LoanAmount         597 non-null    float64
 9   Loan_Amount_Term   597 non-null    float64
 10  Credit_History     597 non-null    float64
 11  Property_Area      597 non-null    object
 12  Loan_Status        597 non-null    object
dtypes: float64(5), int64(1), object(7)
memory usage: 65.3+ KB

In [12]:
LE_object = LabelEncoder()
Loan_Data["Gender"] = LE_object.fit_transform(Loan_Data["Gender"])
Loan_Data["Married"] = LE_object.fit_transform(Loan_Data["Married"])
Loan_Data["Self_Employed"] = LE_object.fit_transform(Loan_Data["Self_Employed"])
Loan_Data["Education"] = LE_object.fit_transform(Loan_Data["Education"])

In [13]:
Loan_Data.head()

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,1,0,0.0,0,0,5849,0.0,146.412162,360.0,1.0,Urban,Y
1,LP001003,1,1,1.0,0,0,4583,1508.0,128.000000,360.0,1.0,Rural,N
2,LP001005,1,1,0.0,0,1,3000,0.0,66.000000,360.0,1.0,Urban,Y
3,LP001006,1,1,0.0,1,0,2583,2358.0,120.000000,360.0,1.0,Urban,Y
4,LP001008,1,0,0.0,0,0,6000,0.0,141.000000,360.0,1.0,Urban,Y

In [14]:
Loan_Data["Property_Area"] = LE_object.fit_transform(Loan_Data["Property_Area"])
Loan_Data["Loan_Status"] = LE_object.fit_transform(Loan_Data["Loan_Status"])
Loan_Data.head()

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,1,0,0.0,0,0,5849,0.0,146.412162,360.0,1.0,2,1
1,LP001003,1,1,1.0,0,0,4583,1508.0,128.000000,360.0,1.0,0,0
2,LP001005,1,1,0.0,0,1,3000,0.0,66.000000,360.0,1.0,2,1
3,LP001006,1,1,0.0,1,0,2583,2358.0,120.000000,360.0,1.0,2,1
4,LP001008,1,0,0.0,0,0,6000,0.0,141.000000,360.0,1.0,2,1

In [15]:
# Train-Test Split
x = Loan_Data.drop(["Loan_ID", "Loan_Status"], axis=1)
y = Loan_Data["Loan_Status"]
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.25, random_state=2)
print(x_train, "\n")
print(y_train, "\n")
print(x_test, "\n")
print(y_test, "\n")

     Gender  Married  Dependents  Education  Self_Employed  ApplicantIncome  \
7         1        1         3.0          0              0             3036
585       1        1         1.0          0              0             4283
173       1        1         0.0          0              0             5708
541       0        0         0.0          0              0             2138
472       1        1         3.0          0              0             4691
..      ...      ...         ...        ...            ...              ...
551       1        1         1.0          1              0             2492
601       1        1         0.0          1              0             2894
510       1        0         0.0          1              0             3598
544       0        1         0.0          1              0             3017
176       1        1         2.0          0              0             2045

     CoapplicantIncome  LoanAmount  Loan_Amount_Term  Credit_History  \
7               2504.0  158.000000             360.0             0.0
585             3000.0  172.000000              84.0             1.0
173             5625.0  187.000000             360.0             1.0
541                0.0   99.000000             360.0             0.0
472                0.0  100.000000             360.0             1.0
..                 ...         ...               ...             ...
551             2375.0  146.412162             360.0             1.0
601             2792.0  155.000000             360.0             1.0
510             1287.0  100.000000             360.0             1.0
544              663.0  102.000000             360.0             1.0
176             1619.0  101.000000             360.0             1.0

     Property_Area
7                1
585              0
173              1
541              1
472              1
..             ...
551              0
601              0
510              0
544              1
176              0

[447 rows x 11 columns]

7      0
585    0
173    1
541    0
472    1
      ..
551    1
601    1
510    0
544    1
176    1
Name: Loan_Status, Length: 447, dtype: int32

     Gender  Married  Dependents  Education  Self_Employed  ApplicantIncome  \
465       1        0         0.0          0              0             6000
148       0        0         0.0          0              0            10000
138       1        0         0.0          0              0            14999
377       1        1         0.0          0              0             4310
184       0        1         0.0          0              0             3625
..      ...      ...         ...        ...            ...              ...
119       0        0         0.0          0              0            10408
202       1        1         3.0          1              0             3992
262       0        0         1.0          0              0             3481
191       1        0         0.0          0              0            12000
416       0        0         1.0          0              0             2600

     CoapplicantIncome  LoanAmount  Loan_Amount_Term  Credit_History  \
465                0.0  140.000000             360.0             1.0
148             1666.0  225.000000             360.0             1.0
138                0.0  242.000000             360.0             0.0
377                0.0  130.000000             360.0             1.0
184                0.0  108.000000             360.0             1.0
..                 ...         ...               ...             ...
119                0.0  259.000000             360.0             1.0
202                0.0  146.412162             180.0             1.0
262                0.0  155.000000              36.0             1.0
191                0.0  164.000000             360.0             1.0
416                0.0  160.000000             360.0             1.0

     Property_Area
465              0
148              0
138              1
377              1
184              1
..             ...
119              2
202              2
262              1
191              1
416              2

[150 rows x 11 columns]

465    1
148    0
138    0
377    1
184    1
      ..
119    1
202    0
262    0
191    0
416    0
Name: Loan_Status, Length: 150, dtype: int32

In [16]:
RFC_obj = RandomForestClassifier()
RFC_obj.fit(x_train, y_train)

RandomForestClassifier()

In [17]:
y_pred_known = RFC_obj.predict(x_train)

In [18]:
# cheacking the accuracy of Loan prediction  classifier model 
metrics.accuracy_score(y_train, y_pred_known)

1.0

In [19]:
y_pred_unknown = RFC_obj.predict(x_test)

In [20]:
#accuracy_score
metrics.accuracy_score(y_test, y_pred_unknown)

0.7666666666666667

In [21]:
# confusion matrix
metrics.confusion_matrix(y_test, y_pred_unknown)

array([[25, 27],
       [ 8, 90]], dtype=int64)